export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const DELETE_MESSAGE='DELETE_MESSAGE';
export const DELETE_ERROR='DELETE_ERROR';
export const CREATE_MESSAGE='CREATE_MESSAGE';
export const CREATE_ERROR='CREATE_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
//magasins
export const MAGASIN_LIST_REQUEST = 'MAGASIN_LIST_REQUEST'
export const MAGASIN_LIST_SUCCESS = 'MAGASIN_LIST_SUCCESS'
export const MAGASIN_LIST_FAIL = 'MAGASIN_LIST_FAIL'

//magasin/details
export const MAGASIN_DETAILS_REQUEST = 'MAGASIN_DETAILS_REQUEST'
export const MAGASIN_DETAILS_SUCCESS = 'MAGASIN_DETAILS_SUCCESS'
export const MAGASIN_DETAILS_FAIL = 'MAGASIN_DETAILS_FAIL'
//ajouter avis
export const MAGASIN_CREATE_REVIEW_REQUEST = 'MAGASIN_CREATE_REVIEW_REQUEST'
export const MAGASIN_CREATE_REVIEW_SUCCESS = 'MAGASIN_CREATE_REVIEW_SUCCESS'
export const MAGASIN_CREATE_REVIEW_FAIL = 'MAGASIN_CREATE_REVIEW_FAIL'
export const MAGASIN_CREATE_REVIEW_RESET = 'MAGASIN_CREATE_REVIEW_RESET'
//err msg mag
export const DELETE_MESSAGE_MAG='DELETE_MESSAGE_MAG'
export const DELETE_ERROR_MAG='DELETE_ERROR_MAG'
//ajouter visite
//ajouter avis
export const MAGASIN_CREATE_VISITE_REQUEST = 'MAGASIN_CREATE_VISITE_REQUEST'
export const MAGASIN_CREATE_VISITE_SUCCESS = 'MAGASIN_CREATE_VISITE_SUCCESS'
export const MAGASIN_CREATE_VISITE_FAIL = 'MAGASIN_CREATE_VISITE_FAIL'
export const MAGASIN_CREATE_VISITE_RESET = 'MAGASIN_CREATE_VISITE_RESET'

//list marchant
export const MAGASINMarchant_LIST_REQUEST='MAGASINMarchant_LIST_REQUEST'
export const MAGASINMarchant_LIST_SUCCESS='MAGASINMarchant_LIST_SUCCESS'
export const MAGASINMarchant_LIST_FAIL='MAGASINMarchant_LIST_FAIL'


//ajout requete
//ajouter avis
export const MAGASIN_CREATE_REQUETE_REQUEST = 'MAGASIN_CREATE_REQUETE_REQUEST'
export const MAGASIN_CREATE_REQUETE_SUCCESS = 'MAGASIN_CREATE_REQUETE_SUCCESS'
export const MAGASIN_CREATE_REQUETE_FAIL = 'MAGASIN_CREATE_REQUETE_FAIL'
export const MAGASIN_CREATE_REQUETE_RESET = 'MAGASIN_CREATE_REQUETE_RESET'
