const magasins = [
  {
    '_id': '1',
    'Nom'	: 'alimentation générale',
    'Wilaya': 16,
    'Commune':'Dar El Beida',	
    'Adresse'	:'cité frère achouri dar elbaida',
    'Telephone':  '666319680', 
    'catégorie': 'Alimentation', 
    'Note':3.5,
    'Latitude': 36.7229,	
    'Longitude': 3.21441,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 12,
    'produits':[
      {
        '_id':'1',
        'nom':'Miel Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':100,
      },
      {
        '_id':'2',
        'nom':'Dattes Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':200,
      },
      {
        '_id':'3',
        'nom':'Miel Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':100,
      },     
       {  '_id':'4',
        'nom':'Miel Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':100,
      },
    ],
  },
  {
    '_id': '2',
    'Nom'	: 'superette djabali',
    'Wilaya': 16,
    'Commune':'Dar El Beida',	
    'Adresse'	:'rue ptt n°16',
    'Telephone':  '561684191', 
    'catégorie': 'Alimentation', 
    'Note':3,
    'Latitude': 36.7129,	
    'Longitude': 3.21659,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 10,
    'produits':[
      {
        '_id':'1',
        'nom':'Miel Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':100,
      },
      {
        '_id':'1',
        'nom':'Miel Algérie',
        'image':'http://127.0.0.1:8000/static/images/produit-standard.jpg',
        'prix':100,
      },
      
    ],
  },
  {  				
    '_id': '3',
    'Nom'	: 'supérette royal',
    'Wilaya': 16,
    'Commune':'Alger-Centre',	
    'Adresse'	:'03 rue lili',
    'Telephone':  '550711324', 
    'catégorie': 'Alimentation', 
    'Note':	1,
    'Latitude': 36.7734,	
    'Longitude': 	3.06476	,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 12,
  },
  {	
    '_id': '4',
    'Nom'	: 'supérette karie bleu',
    'Wilaya': 16,
    'Commune':'Alger-Centre',	
    'Adresse'	:'compiratifeb el ansoure',
    'Telephone':  '666319680', 
    'catégorie': 'Alimentation', 
    'Note':4,
    'Latitude': 36.6993,	
    'Longitude': 	3.07769,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 12,
  },
  { 						
    '_id': '5',
    'Nom'	: 'LE HOGGAR',
    'Wilaya': 16,
    'Commune':'Alger Centre',	
    'Adresse'	:'66 Rue Didouche Mourad Algiers ',
    'Telephone':  '023 50 46 10', 
    'catégorie': 'Artisanat', 
    'Note':3,
    'Latitude': 36.7498,	
    'Longitude': 2.88402,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 12,
  },
  {
    '_id': '6',
    'Nom'	: 'Arts Gallery',
    'Wilaya': 16,
    'Commune':'Alger Centre',	
    'Adresse'	:'48 B Rue Didouche Mourad Algiers',
    'Telephone':  '0555 65 84 52 ', 
    'catégorie': 'Artisanat', 
    'Note':	3,
    'Latitude': 36.7498,	
    'Longitude': 2.88402,
    'Ouverture': '07:00',
    'Fermeture': '23:00',
    'image': 'http://127.0.0.1:8000/static/images/shop-standart.jpg',
    'numReviews': 12,
  },
]


export default magasins
