# Generated by Django 3.1.5 on 2021-05-12 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210511_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nom', models.CharField(max_length=56)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('nom', models.CharField(max_length=56)),
                ('adresse', models.CharField(blank=True, max_length=70, null=True)),
                ('telephone', models.CharField(blank=True, max_length=17, null=True)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('overture', models.TimeField(blank=True, null=True)),
                ('fermeture', models.TimeField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default='/shop-standart.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.categorie')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.communes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('nom', models.CharField(max_length=56)),
                ('image', models.ImageField(blank=True, default='/produit-standard.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitMag',
            fields=[
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.produit')),
            ],
        ),
    ]
