# Generated by Django 3.1.5 on 2021-05-18 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210512_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('Visite_duration', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
