# Generated by Django 3.1.5 on 2021-06-05 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_magasin_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='prods',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
