# Generated by Django 3.1.5 on 2021-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20210605_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='prods',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
