# Generated by Django 3.1.5 on 2021-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20210605_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='prods',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
