# Generated by Django 3.1.5 on 2021-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20210612_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
